name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Ubuntu ${{ matrix.compiler }} C++${{ matrix.cpp }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        cpp: [20]
        compiler: [GCC, Clang]
        
    env:
      CPP_STANDARD: ${{ matrix.cpp }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          
      - name: set up Clang
        run: |
          sudo apt update
          sudo apt install clang-12 clang-tools-12 
        
        if: matrix.compiler == 'Clang'

      - name: set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64
        if: matrix.compiler == 'GCC'
      
      - name: configure
        run: cmake -S . -B build -DTP_BUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4

      - name: test
        run: |
          cd build
          ctest --build-config Debug
